import type { Metadata } from "next";

import "../../shared/mocks/server/enable-server-mock";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className="antialiased">{children}</body>
    </html>
  );
};
